import { createServer } from 'node:http';
import { readJson } from './ioc-utils.mjs';

const PORT = Number(process.env.TAXII_PORT ?? 7000);
const HOST = process.env.TAXII_HOST ?? '0.0.0.0';
const BUNDLE_PATH = process.env.TAXII_BUNDLE_PATH ?? 'out/stix-bundle.json';
const API_ROOT = process.env.TAXII_API_ROOT ?? `http://localhost:${PORT}/taxii2/`;
const COLLECTION_ID = 'tisp-1';

const taxiiHeaders = {
  'content-type': 'application/taxii+json;version=2.1',
};

const send = (res, status, body) => {
  res.writeHead(status, taxiiHeaders);
  res.end(`${JSON.stringify(body, null, 2)}\n`);
};

const notFound = (res) => send(res, 404, {
  title: 'Not found',
  description: 'The requested TAXII resource does not exist.',
});

const loadBundle = async () => {
  try {
    return await readJson(BUNDLE_PATH);
  } catch {
    return { type: 'bundle', id: 'bundle--tisp-empty', objects: [] };
  }
};

const server = createServer(async (req, res) => {
  const url = new URL(req.url, API_ROOT);

  if (req.method !== 'GET') {
    send(res, 405, { title: 'Method not allowed' });
    return;
  }

  if (url.pathname === '/taxii2/' || url.pathname === '/taxii2') {
    send(res, 200, {
      title: 'TISP Nexus TAXII',
      description: 'Read-only TAXII 2.1 endpoint for sanitized STIX bundles.',
      default: `${API_ROOT}collections/`,
      api_roots: [API_ROOT],
    });
    return;
  }

  if (url.pathname === '/taxii2/collections/' || url.pathname === '/taxii2/collections') {
    send(res, 200, {
      collections: [
        {
          id: COLLECTION_ID,
          title: 'TISP Nexus Indicators',
          description: 'Sanitized TLP-controlled CTI indicators generated by tisp-tools.',
          can_read: true,
          can_write: false,
          media_types: ['application/stix+json;version=2.1'],
        },
      ],
    });
    return;
  }

  if (url.pathname === `/taxii2/collections/${COLLECTION_ID}/objects/` || url.pathname === `/taxii2/collections/${COLLECTION_ID}/objects`) {
    const bundle = await loadBundle();
    send(res, 200, {
      more: false,
      objects: bundle.objects ?? [],
    });
    return;
  }

  notFound(res);
});

server.listen(PORT, HOST, () => {
  console.log(`TISP TAXII server listening on http://${HOST}:${PORT}/taxii2/`);
});
